name:  CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name:  Run Selenium + Pytest and Generate HTML Report

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Selenium tests
        run: |
          mkdir -p reports
          pytest --disable-warnings -v --html=reports/report.html --self-contained-html

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-pytest-report
          path: reports/report.html

  deploy:
    name: Deploy HTML report to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v4

      - name:  Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: selenium-pytest-report
          path: public

      - name:  Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
